### ISSUE TITLE
Change log?

### ISSUE THREAD

**Issue by mcoolidge** [aliasadidev/vsocde-npm-gui#4]
Would it be possible to link to the change log?

As an example the github dependabot brings them into PRs.

![image](https://user-images.githubusercontent.com/986728/103959461-bc4d0e00-511d-11eb-852f-ba85220e1542.png)

**Comment by aliasadidev** [comment]
Why do wanna do that?

**Comment by aliasadidev** [comment]
Why do you wanna do that?

**Comment by mcoolidge** [comment]
It will help me determine if I want to update the package.

**Comment by aliasadidev** [comment]
You can link to the changelog.
