### ISSUE TITLE
The extension doesn't support proxy

### ISSUE THREAD

**Issue by hansWurst-creator** [aliasadidev/vsocde-npm-gui#7]
Thanks for the awesome extension.

I am having a bit of trouble getting your extension to work though. The extension seams to fail to make a connection with the internet.  I can access the link just fine in a browser.

One probable culprit could be, that I am behind a company proxy. Do the proxy settings of vscode get used to establish the connection?

![image](https://user-images.githubusercontent.com/70693364/104293984-f2441680-54be-11eb-95de-6e35c4bda537.png)

**Comment by aliasadidev** [comment]
The extension doesn't support proxy. I will add the proxy support for the next release.

**Comment by aliasadidev** [comment]
Are you set the proxy setting in VSCode?  [vscode doc](https://code.visualstudio.com/docs/getstarted/settings)

**Comment by aliasadidev** [comment]
The other extensions work well?
@hansWurst-creator

**Comment by aliasadidev** [comment]
This error sometimes occurs when you have low internet speed. 
Increase the timeout value in the setting.json

//The maximum duration for completing a request from this extension
"nugetpackagemanagergui.nuget.requestTimeout": 9000,

**Comment by hansWurst-creator** [comment]
That's my proxy settings. If I don't set those I am unable to do a dotnet restore.
![image](https://user-images.githubusercontent.com/70693364/104315368-23cadb00-54db-11eb-89b4-b8bf786d323f.png)

I will try with a longer timeout.

**Comment by aliasadidev** [comment]
I've added this feature. I will publish it in the next release.

**Comment by hansWurst-creator** [comment]
Thanks. I will give you feedback when I get a chance to try it out.

**Comment by aliasadidev** [comment]
I've published the new version of the package.
@hansWurst-creator

**Comment by hansWurst-creator** [comment]
sadly I am getting this response. Is there a way I can look at the actual json response that the addon receives?
![image](https://user-images.githubusercontent.com/70693364/104891819-b4893700-5971-11eb-8063-55f93d44c69a.png)

**Comment by aliasadidev** [comment]
I've tested with Tor proxy, but I didn't get any error.
If possible for you, create an empty folder with one csproj file that contains the following content:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Serilog.Enrichers.Thread" Version="2.0.0-beta-700"/>
  </ItemGroup>
</Project>
```

and test it again.

**Comment by aliasadidev** [comment]
This extension sends batch requests to the Nuget server and then wait for them. In your case, the proxy rejects some requests (Maybe!).
