### ISSUE TITLE
support several nuget servers ?

### ISSUE THREAD

**Issue by TomyCesaille** [aliasadidev/vsocde-npm-gui#9]
Hi,
The current status of the extension seems to allow the customization of the nuget source thanks to `nugetpackagemanagergui.nuget.searchPackage.url`.

In my ends, I am using 2 sources that are fed through `nuget.config`.
I was wondering if you plan on supporting several sources from your config or from `nuget.config` file (would be even better).

I could help on that by the way, I'm issuing in advance in case this is already plan/ongoing.

And thanks for this work so far !
Regards,

**Comment by aliasadidev** [comment]
Hi @TomyCesaille 
Your request sounds great!
I've added this feature, and I think it needs some tests to be published.
If you can test it, I will appreciate it.

**Comment by aliasadidev** [comment]
![image](https://user-images.githubusercontent.com/6399165/105873695-ffa9e680-6010-11eb-8917-66e340adc82f.png)


Both SearchPackage and PackageVersionsUrl properties are list now

**Comment by aliasadidev** [comment]
the branch is [support-several-nuget-servers](https://github.com/aliasadidev/vsocde-npm-gui/tree/support-several-nuget-servers)

**Comment by TomyCesaille** [comment]
On my way to test it out, you rock !

**Comment by TomyCesaille** [comment]
# Report

## Context

I use the official Nuget + a private corporate BaGet server.

## Results

* [x] Existing Unit tests works (didn't look in the detail
* [x] Identify versions of packages in source A or in source B
* [x] Identify not-up-to-date packages in source A or in source B
* [x] Update a package from source A or in source B
* [x] Search a package in Source A AND source B (only with PR https://github.com/aliasadidev/vsocde-npm-gui/pull/10)
* [x] Install a package from source A or in source B

For the record, here are my links for BaGet:

* **packageVersionsUrl**: `http://xxx/v3/package/{{packageName}}/index.json`
* **searchPackage.url**: `http://xxx/v3/search` 

Thank you for your work again ;)
Glad to see I can use this extension with my team soon !
